### ISSUE TITLE
scrollWithoutAnimationTo is deprecated. Use scrollTo instead

### ISSUE THREAD

**Issue by jiangbophd** [rgovindji/react-native-atoz-list#14]
Dear,

Firstly, thanks for your effort, it is very good.

I find there is warning for scroll. I try to change scrollTo, but there is not good. so solwly, I did not find any reasons. 

Do you have any ideas for this? it is afraid not wok in the future.

Thanks!

**Comment by rgovindji** [comment]
Hi thank you!

This is a known issue, there may be a new solution now but I haven't had
time to check. Please feel free to submit a PR if you find a solution.


ᐧ

**Comment by gianpieroc** [comment]
This issue is done. Can we have a new release with this? @rgovindji
