### ISSUE TITLE
letters stops scrolling when nested in a ScrollView 

### ISSUE THREAD

**Issue by revh** [rgovindji/react-native-atoz-list#26]
Hi,

if i put this component in a <ScrollView>, when i touch the letters the scroll stops immediately after the first scroll.

This happens also if i set false to scrollEnabled prop

```
<View style={{ flex: 1 }}>
  <ScrollView scrollEnabled={false} contentContainerStyle={{ flex: 1 }}>
    <AtoZList
      sectionHeaderHeight={20}
      cellHeight={60}
      data={myData}
      renderCell={this._renderCellComponent}
      renderSection={this._renderSectionComponent}
    />
  </ScrollView>
</View>
```

Thank you

**Comment by eugenehp** [comment]
seeing same thing, it works fine on simulator but does nothin on real device.
