### ISSUE TITLE
code need update with last react version

### ISSUE THREAD

**Issue by alainib** [rgovindji/react-native-atoz-list#27]
Hello 
I'm testing this repo with your example files.
with last react version code need fix  :  

-----------------
AlphabetPicker.js

from 
`import React, { Component, PropTypes } from 'react';`
To 
`import React, { Component } from 'react';
import PropTypes from "prop-types";`

-----------------
AtoZlist.js

from 
`import React, { Component, PropTypes } from 'react';`
To 
`import React, { Component } from 'react';
import PropTypes from "prop-types";`

--------------
FixedHeightWindowedListView.js

add `import PropTypes from "prop-types";`

line 184  from
`this.scrollRef.scrollWithoutAnimationTo(startY); // this.scrollRef.scrollTo({x: 0, y: startY, animation: false});`
to

`//this.scrollRef.scrollWithoutAnimationTo(startY);`
`this.scrollRef.scrollTo({x: 0, y: startY, animation: false});`

line 374 
from

`FixedHeightWindowedListView.propTypes = {
  dataSource: React.PropTypes.object.isRequired,
  renderCell: React.PropTypes.func.isRequired,
  renderSectionHeader: React.PropTypes.func,
  incrementDelay: React.PropTypes.number,
  initialNumToRender: React.PropTypes.number,
  maxNumToRender: React.PropTypes.number,
  numToRenderAhead: React.PropTypes.number,
  numToRenderBehind: React.PropTypes.number,
  pageSize: React.PropTypes.number,
};`

to 
`FixedHeightWindowedListView.propTypes = {
  dataSource: PropTypes.object.isRequired,
  renderCell: PropTypes.func.isRequired,
  renderSectionHeader: PropTypes.func,
  incrementDelay: PropTypes.number,
  initialNumToRender: PropTypes.number,
  maxNumToRender: PropTypes.number,
  numToRenderAhead: PropTypes.number,
  numToRenderBehind: PropTypes.number,
  pageSize: PropTypes.number,
};`

**Comment by rgovindji** [comment]
Make a PR and I'll update the package

**Comment by alainib** [comment]
i will but sorry i never do this. how to do it please

**Comment by alainib** [comment]
the code from npm is different from the github code. 

for example the import is already fixed in AlphabetPicker.js in github but not on the npm version

**Comment by siddhisuthar** [comment]
@rgovindji , can you push the updated code to npm registry and make a new release?

**Comment by kamleshnarola** [comment]
Thank you @alainib for pointing this issue out.Facing the same issue while using  react-native-atoz-list as well as react-native-alphabetlistview. I am new to react-native and stuck around it from a long time.Didn't knew what the issue was though. Thank god you opened the issue. 
@rgovindji This looks like a great library to be integrate with any project.It will be really great if you can fix it as soon as possible.Thanks in Advance.

**Comment by rgovindji** [comment]
Yeah I can push a new version to NPM today

**Comment by rgovindji** [comment]
Please check NPM for 1.0.3 now
