### ISSUE TITLE
"Alphabet" is read-only 

### ISSUE THREAD

**Issue by Max2839** [rgovindji/react-native-atoz-list#33]
Error: Error: "Alphabet" is read-only

This error is located at:
    in AlphabetPicker (at AtoZList.js:76)

**Comment by shouhuori** [comment]
Same error.

**Comment by shouhuori** [comment]
@Mohsen2839  in AtoZlist.js, line 76:
```
 <View style={styles.alphabetSidebar}>
        <AlphabetPicker
          // alphabet={this.state.alphabet}
          onTouchLetter={this._onTouchLetter.bind(this)} />
      </View>
```

**Comment by Max2839** [comment]
just change this line in AlphabetPicker.js : 
const Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('');
to 
var Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('');

**Comment by rgovindji** [comment]
Latest update changed alphabet to non const
