### ISSUE TITLE
Hi, tested with 15000 records and had a lot of blank space

### ISSUE THREAD

**Issue by lander854** [rgovindji/react-native-atoz-list#39]
How to avoid this slow blank spaces to happend? used the example provided and a larger dataset ( 15000 contacts with name, email and id)

**Comment by danmun** [comment]
Random comment passing through. Partially load the dataset from your server or local storage as you need. Don't load the entire list in one go, nobody does that for such large datasets.

**Comment by rgovindji** [comment]
That sounds like way too many records to be loaded in a single go. Try react native flatlist instead it may have better support for what you are looking for.
