### ISSUE TITLE
onEndReached 

### ISSUE THREAD

**Issue by sibelius** [rgovindji/react-native-atoz-list#4]
I would like to lazy load my contacts from an api,

is it possible to have an onEndReached like in ListView?

**Comment by rgovindji** [comment]
I haven't tried using onEndReached and it looks like the method isn't exposed but PR is welcome.

I do filter on key stroke which has pretty great performance. I simply pass in a filtered set of data to the list so adding data onEndReached should have similar performance. If I have time in the next few days I'll try it out.

**Comment by sibelius** [comment]
what do u think of this component: https://github.com/facebook/react-native/blob/master/Libraries/Experimental/WindowedListView.js

I think it shares the same ideas of fixed height windowed list view by @brentvatne

it has `onEndReached` support and it could be a little bit faster
